trigger: none

resources:
  repositories:
  - repository: templates
    type: github
    name: mgrlabs/azdo-pipeline-templates # Change with the username and git the repository where your common templates are
    # ref: refs/tags/v1.0.0 # Do not forget to specify the correct tag for your common templates repository
    endpoint: mgrlabs # Update with the end point connection

variables:
  serviceConnection: 'mgrlabs - Sandbox'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Dev
    variables:
      backendConfig: 'dev.tfbackend'
      workingDirectory: 'environments/dev'
    jobs:
    - template: terraform/plan.yml@templates
      # parameters:
      #   preBuild:
      #     - task: Bash@3
      #       displayName: 'Add custom configuration'
      #       inputs:
      #         targetType: 'inline'
      #         script: |
      #           echo Add a specific configuration