trigger:
- master
- feature/*

pr:
- master

resources:
  repositories:
  - repository: templates
    type: github
    name: mgrlabs/azdo-pipeline-templates # Change with the username and git the repository where your common templates are
    # ref: refs/tags/v1.0.0 # Do not forget to specify the correct tag for your common templates repository
    endpoint: mgrlabs # Update with the end point connection

variables:
  serviceConnection: 'mgrlabs - Sandbox'

pool:
  vmImage: 'ubuntu-latest'

stages:

########################
# Dev Environment
########################

  - stage: 'dev_test'
    variables:
      backendConfig: 'dev.tfbackend'
      workingDirectory: 'environments/dev'
      environment: 'dev'
    jobs:
    - template: terraform/test.yml@templates
  - stage: 'dev_plan'
    variables:
      backendConfig: 'dev.tfbackend'
      workingDirectory: 'environments/dev'
      environment: 'dev'
    jobs:
    - template: terraform/plan.yml@templates
  - stage: 'dev_apply'
    variables:
      backendConfig: 'dev.tfbackend'
      workingDirectory: 'environments/dev'
      environment: 'dev'
    jobs:
    - template: terraform/apply.yml@templates